### ISSUE TITLE
scrollbar malfunction

### ISSUE THREAD

**Issue by sevenjames** [EvaisaGiac/Twitch-Extended#1]
The config menu scroll bar does not work. The only way to scroll the configuration page is with the mouse wheel.

Expected behavior: can click or drag the scroll bar to scroll the configuration page.

Actual behavior: cannot click or drag the scroll bar to scroll the configuration page. When mouse cursor is moved over the scroll bar, a buzzing sound is heard; sounds like the normal scrolling sound playing on repeat at max fps.

Example of a well behaved Noita scrollbar is in the in-game release notes, accessible from the main menu.

Speculation: might this bug be in the new Config Lib dependency?

Sample: https://youtu.be/suFApaS4y4I

Edit to add: As shown in the video, Noita is up to date and only Twitch Extended and Config Lib are loaded.

**Comment by EvaisaGiac** [comment]
Fixed it.

**Comment by EvaisaDev** [comment]
Fixed in the new version of Config Lib and Twitch Extended.
Make sure to update your Config Lib to fix the scroll bar issue.
