### ISSUE TITLE
Usernames containing special characters will not show up in in-game chat and are unable to vote

### ISSUE THREAD

**Issue by PounceVT** [EvaisaGiac/Twitch-Extended#8]
![image](https://user-images.githubusercontent.com/9016472/147422788-0239e49a-8929-40db-93f8-a30e59d5d020.png)

As depicted above, the user `最乖的和牛 (best_wagyu)` sends a message. Their username is not displayed in the in-game chat.
The user also tries to vote on the current event, which is not working due to their special display name.

This bug happens for users that have set-up a display name that is entirely Japanese, Chinese or Korean.
Normally Twitch only allows you to change the capitalization of the display name, however when Twitch's language is set to JP, CN or KR, the user can specify any name that they want, including non-alphanumeric characters.
See [this blog post](https://blog.twitch.tv/en/2016/08/22/localized-display-names-e00ee8d3250a/) for more info.

**Comment by EvaisaDev** [comment]
Note that you are using Twitch Lib in the screenshot which has it's own instance of the IRC parser so I have to patch it there too.

**Comment by PounceVT** [comment]
Thanks! Just checked the latest version and this issue seems to be resolved.
